<a href="https://colab.research.google.com/github/yogesh-bhattarai/python_class/blob/master/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [2]:
!pip install numpy

In [4]:
a= np.array([1,2])

In [5]:
print(a)

[1 2]


In [6]:
type(a)

numpy.ndarray

In [7]:
b= np.array([[1,2,3],[4,5,6]])

In [8]:
type(b)

numpy.ndarray

In [9]:
zero= np.zeros((2,3))

In [10]:
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
ones= np.ones((3,3))

In [12]:
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
rand= np.random.rand(2,2)

In [18]:
rand

array([[0.9254563 , 0.46955794],
       [0.63218485, 0.26270831]])

In [19]:
arr1= np.arange(10)

In [20]:
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
arr2= np.linspace(1,10,3)
print(arr2)

[ 1.   5.5 10. ]


In [28]:
x= np.array([10,20,30])
y=np.array([1,2,3])

add= x+y
mul=x*y
div= x/y

In [30]:
div

array([10., 10., 10.])

In [34]:
data= np.array([10,20,30,40,50])
mean_val= np.mean(data)
median_val= np.median(data)
std_val= np.std(data)
sum_val= np.sum(data)

In [35]:
mean_val

np.float64(30.0)

In [36]:
median_val

np.float64(30.0)

In [37]:
std_val

np.float64(14.142135623730951)

In [38]:
sum_val

np.int64(150)

In [41]:
arr= np.arange(12)
reshaped= arr.reshape(3,4)
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [42]:
data

array([10, 20, 30, 40, 50])

In [43]:
filtered= data[data>20]

In [44]:
filtered

array([30, 40, 50])

In [48]:
data[-1]

np.int64(50)

In [49]:
data

array([10, 20, 30, 40, 50])

In [51]:
np.max(data)

np.int64(50)

In [52]:
sorted_arr= np.sort(np.array([2,3,6,10,1,90,60,40]))

In [53]:
print(sorted_arr)

[ 1  2  3  6 10 40 60 90]


In [54]:
sorted_arr

array([ 1,  2,  3,  6, 10, 40, 60, 90])

In [56]:
sorted_arr[0:4]

array([1, 2, 3, 6])

In [57]:
arr= [1,1,2,3,3,3,4,4,5,5,6,6,67,7,8,9,9,9,99,]
np.unique(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 67, 99])

In [63]:
r2= np.random.randint(1,20,5)
print(r2)

[ 6  3  4  5 13]


In [64]:
a= np.array([1,2])
b= np.array([3,4])
print(np.concatenate((a,b)))

[1 2 3 4]
